version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./entrypoint.sh
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
    volumes:
      - ./restaurant_visits_project:/restaurant_visits_diary/restaurant_visits_project
    ports:
      - "8000:8000"
    container_name: restaurant_diary_web

  db:
    image: postgres
    environment:
      POSTGRES_DB: diary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres
      timeout: 20s
      retries: 3
    container_name: restaurant_diary_db
    volumes:
      - db-data:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    restart: unless-stopped
    container_name: restaurant_diary_pg_admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    logging:
      driver: none
    depends_on:
      - db

volumes:
  db-data:
  pgadmin-data:
