# Generated by Django 4.0.4 on 2022-05-22 16:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveConstraint(
            model_name='restaurant',
            name='unique_user_restaurant',
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('creator', 'name')},
        ),
    ]
